spring.application.name=cricket-team-management
spring.datasource.url=jdbc:mysql://localhost:3306/cricketdb
spring.datasource.username=root
spring.datasource.password=sowmiya123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080